### ISSUE TITLE
Usage without request and response

### ISSUE THREAD

**Issue by sobolevn** [bradmontgomery/django-querycount#16]
Hi, thanks for this awesome package. I really enjoy using it.

But I have a question about how to use this package without a `request` instance?
Here are some examples where I need this:
1. `celery` tasks, in `DEBUG` I want them to print the query count in the same manner middleware does
2. `telegram` bots, we do develop some telegram bots on top of `django`. `telegram` bots serve as clients which does not have any `django`'s `request` instance. But I still want this app to work

Thanks!

**Comment by bradmontgomery** [comment]
Hi @sobolevn, this is an interesting idea, and would probably be doable with a little effort. The overall design of this package assumes it's meant to run as middleware which necessarily assumes you've got a request & a response, but the core query-counting happens in a the [_count_queries() method](https://github.com/bradmontgomery/django-querycount/blob/master/querycount/middleware.py#L64).  We could probably pull that out into a standalone function that would allow you to use it in other ways.

Unfortunately, my schedule is pretty full for a while. If you want try implementing this, I'd be happy to review your code along the way, then pull your changes back in.

**Comment by sobolevn** [comment]
Ok, @bradmontgomery, here's my plan:

1. Separate [`count_queries`](https://github.com/bradmontgomery/django-querycount/blob/master/querycount/middleware.py#L64) into its own `queries.QueriesCounter` class
2. Separate [`print_num_queries`] and  [`stats_table`](https://github.com/bradmontgomery/django-querycount/blob/master/querycount/middleware.py#L117) into `reporter.ConsoleReporter` class
3. Update docs
4. Write tests 

How I see an API for the new feature? Something like this:

```python
def count_and_report_queries(reporter_class=None):
    if reporter_class is None:
        reporter_class = ConsoleReported
   stats = QueryCounter().count()
   reporter_class(stats).create_report()
   return stats
```

**Comment by bradmontgomery** [comment]
Closing this as `django-assert-num-queries` from `pytest` ☝️ seems a better approach.
