### ISSUE TITLE
repeated calls

### ISSUE THREAD

**Issue by JostCrow** [bradmontgomery/django-querycount#7]
Maybe it is a possibility to show the repeated calls. This way you can easily see that there are duplicated calls. (like they show in debug toolbar)

**Comment by bradmontgomery** [comment]
@JostCrow thanks for the idea. I have mixed feelings on this though, because it seems like we're already pretty constrained with the amount of output that get's displayed. I really like being able to quickly glance at the terminal to identify issues, and then when I see a lot of queries, I head over the debug toolbar for diagnosis.

Having said that, do you have something in mind? How would you expect to see this information conveyed in `querycount`'s output?  If we can somehow indicate that we've got lots of duplicate queries without filling up the screen with text I'd consider it!

**Comment by JostCrow** [comment]
Hello Sorry for my late response. If the queries will be displayed it will take a lot of space. What I had in mind was something like this.
```
------------------------------------------------------------------
| Type | DB | Reads | Writes | Totals | Duplicates |
------------------------------------------------------------------
|         |        |   102  |     0      |   102   |       90        |
-----------------------------------------------------------------
```
This will not use a lot of space. And maybe there could be an aditional middleware class that you can add that will display the query that is counted as a duplicate and only shows the first of the duplicates. like this.
```
--------------------------------------------------
| Type | DB | Reads | Writes | Totals |
-------------------------------------------------
|         |        |   102  |     0      |   102   |
-------------------------------------------------
```
*optional*
Duplicated 45 times:
SELECT * FROM users WHERE id = 3
Duplicated 45 times:
SELECT * FROM site WHERE user_id = 3

The reason that I am asking for this is when you do not have django debug toolbar is not available for instance a rest API.

**Comment by bradmontgomery** [comment]
Ok, cool. I think this kind of thing is doable, though I want to give some additional thought to displaying the queries.

> The reason that I am asking for this is when you do not have django debug toolbar is not available for instance a rest API.

This is enough to convince me. I'm using django-rest-framework and during dev you _can_ have a debug toolbar pane, but I've certainly worked on projects where this wasn't the case.

It'll be a few days before I have a chance to dig into this, so until then feel free to share any additional thoughts on these features.

**Comment by bradmontgomery** [comment]
New release (0.4.0) is on pypi. Check out the updated settings in the README, and let me know whether or not this update works for you.

**Comment by JostCrow** [comment]
Thanks. It looks great. I will test it tomorrow

**Comment by JostCrow** [comment]
It works perfectly. Thank you.

**Comment by JostCrow** [comment]
After testing it a bit further I found a bug.

------|-----------|----------|----------|----------|------------|
| Type | Database  |   Reads  |  Writes  |  Totals  | Duplicates |
|------|-----------|----------|----------|----------|------------|
|------|-----------|----------|----------|----------|------------|
| RESP |  default  |    6     |    0     |    6     |     19     |
|------|-----------|----------|----------|----------|------------|
Total queries: 6 in 0.0797s


Repeated 19 times.
SELECT ....

It seems to remember the previous duplicates instead of the displaying the current one.

**Comment by bradmontgomery** [comment]
Hrm. Ok. Will check into it.

**Comment by bradmontgomery** [comment]
@JostCrow This should be working correctly now. A new version (0.4.1) is up on pypi: https://pypi.python.org/pypi/django-querycount/0.4.1

Thanks for testing & reporting this!
